# Generated by Django 2.1.7 on 2019-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(default=None, max_length=200)),
                ('date_of_est', models.DateField(verbose_name='date')),
                ('moto', models.CharField(default=None, max_length=400)),
                ('party_leader', models.CharField(default=None, max_length=200)),
                ('founded_by', models.CharField(default=None, max_length=200)),
                ('party_logo_name', models.CharField(default=None, max_length=200)),
                ('no_of_votes', models.IntegerField(default=0)),
                ('party_logo', models.ImageField(blank=True, default='../media/image/abc.jpg', null=True, upload_to='image')),
                ('leader', models.ImageField(blank=True, default='../media/image/abcd.jpg', null=True, upload_to='image')),
            ],
        ),
    ]
